-- simRobomaster lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simRobomaster=require('simSkel')

function simRobomaster.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simRobomaster'][funcName]=wrapperGenerator(_G['simRobomaster'][funcName])
    end

end

sim.registerScriptFuncHook('sysCall_init','simRobomaster.__addTypeCheck',true)

return simRobomaster
